# Generated by Django 5.0.7 on 2024-07-18 22:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CarBrand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('logo', models.ImageField(upload_to='car_logos/')),
            ],
        ),
        migrations.CreateModel(
            name='CarModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.carbrand')),
            ],
        ),
        migrations.CreateModel(
            name='CarGeneration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.carmodel')),
            ],
        ),
        migrations.CreateModel(
            name='Engine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('photo', models.ImageField(upload_to='engine_photos/')),
                ('fuel_type', models.CharField(choices=[('Petrol', 'Бензин'), ('Disel', 'Дизель')], max_length=50)),
                ('power', models.IntegerField()),
                ('volume', models.FloatField()),
                ('state_of_origin', models.CharField(max_length=100)),
                ('condition', models.CharField(choices=[('NEW', 'Новый'), ('USED', 'Б/у')], max_length=50)),
                ('generation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.cargeneration')),
            ],
            options={
                'ordering': ['condition', 'state_of_origin'],
            },
        ),
    ]
