# Generated by Django 5.0.7 on 2024-07-18 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='engine',
            name='generation',
        ),
        migrations.AddField(
            model_name='engine',
            name='generations',
            field=models.ManyToManyField(to='main.cargeneration'),
        ),
        migrations.AlterField(
            model_name='engine',
            name='fuel_type',
            field=models.CharField(choices=[('Petrol', 'Бензин'), ('Diesel', 'Дизель')], max_length=50),
        ),
    ]
