# Generated by Django 5.0.7 on 2024-07-20 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_remove_engine_generation_engine_generations_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='engine',
            name='condition',
            field=models.CharField(choices=[('Новый', 'Новый'), ('Б/у', 'Б/у')], max_length=50),
        ),
        migrations.AlterField(
            model_name='engine',
            name='fuel_type',
            field=models.CharField(choices=[('Бензин', 'Бензин'), ('Дизель', 'Дизель')], max_length=50),
        ),
    ]
