# Generated by Django 5.0.7 on 2024-07-21 10:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_engine_price_engine_price_order'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='carbrand',
            options={'verbose_name': 'Марку', 'verbose_name_plural': 'Марки'},
        ),
        migrations.AlterModelOptions(
            name='cargeneration',
            options={'verbose_name': 'Поколение', 'verbose_name_plural': 'Поколения'},
        ),
        migrations.AlterModelOptions(
            name='carmodel',
            options={'verbose_name': 'Модель', 'verbose_name_plural': 'Модели'},
        ),
        migrations.AlterModelOptions(
            name='engine',
            options={'ordering': ['condition', 'state_of_origin'], 'verbose_name': 'Двигатель', 'verbose_name_plural': 'Двигатели'},
        ),
        migrations.RemoveField(
            model_name='engine',
            name='power',
        ),
        migrations.AlterField(
            model_name='carbrand',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='cargeneration',
            name='model',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.carmodel', verbose_name='Модель'),
        ),
        migrations.AlterField(
            model_name='cargeneration',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='carmodel',
            name='brand',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.carbrand', verbose_name='Марка'),
        ),
        migrations.AlterField(
            model_name='carmodel',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='engine',
            name='condition',
            field=models.CharField(choices=[('Новый', 'Новый'), ('Б/у', 'Б/у')], max_length=50, verbose_name='Состояние'),
        ),
        migrations.AlterField(
            model_name='engine',
            name='fuel_type',
            field=models.CharField(choices=[('Бензин', 'Бензин'), ('Дизель', 'Дизель')], max_length=50, verbose_name='Тип топлива'),
        ),
        migrations.AlterField(
            model_name='engine',
            name='generations',
            field=models.ManyToManyField(to='main.cargeneration', verbose_name='Поколения в которых устанавливался'),
        ),
        migrations.AlterField(
            model_name='engine',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='engine',
            name='photo',
            field=models.ImageField(upload_to='engine_photos/', verbose_name='Фото'),
        ),
        migrations.AlterField(
            model_name='engine',
            name='price',
            field=models.FloatField(default=0, verbose_name='Цена'),
        ),
        migrations.AlterField(
            model_name='engine',
            name='price_order',
            field=models.FloatField(default=0, verbose_name='Цена под заказ'),
        ),
        migrations.AlterField(
            model_name='engine',
            name='state_of_origin',
            field=models.CharField(max_length=100, verbose_name='Страна производитель'),
        ),
        migrations.AlterField(
            model_name='engine',
            name='volume',
            field=models.FloatField(verbose_name='Объем двигателя'),
        ),
    ]
