# Generated by Django 5.0.7 on 2024-07-21 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_carbrand_options_alter_cargeneration_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='engine',
            name='fuel_type',
            field=models.CharField(choices=[('Бензин', 'Бензин'), ('Дизель', 'Дизель')], default='Бензин', max_length=50, verbose_name='Тип топлива'),
        ),
    ]
