# Generated by Django 5.0.7 on 2024-08-28 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_alter_engine_fuel_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('engine', models.CharField(max_length=100, verbose_name='Двигатель')),
                ('phone', models.CharField(max_length=15, verbose_name='Номер телефона')),
                ('status', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Заказы',
                'verbose_name_plural': 'Заказ',
            },
        ),
    ]
