# Generated by Django 5.0.7 on 2024-08-28 11:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_order'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Order',
            new_name='OrderEngine',
        ),
    ]
